version: '3'
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 3000:3000
    depends_on:
      - backend
  db:
    container_name: db_products_management
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password